export const asyncAuthTypes = {
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE: "REGISTRATION_FAILURE",

  GET_ME_FAILURE: "GET_ME_FAILURE",
  GET_ME_SUCCESS: "GET_ME_SUCCESS",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",
};

export const asyncFolderTypes = {
  GET_MY_FOLDERS_SUCCESS: "GET_MY_FOLDERS_SUCCESS",
  GET_MY_FOLDERS_FAILURE: "GET_MY_FOLDERS_FAILURE",

  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  CREATE_FOLDER_FAILURE: "CREATE_FOLDER_FAILURE",

  RENAME_FOLDER_SUCCESS: "RENAME_FOLDER_SUCCESS",
  RENAME_FOLDER_FAILURE: "RENAME_FOLDER_FAILURE",

  GET_FOLDER_CHILDREN_SUCCESS: "GET_FOLDER_CHILDREN_SUCCESS",
  GET_FOLDER_CHILDREN_FAILURE: "GET_FOLDER_CHILDREN_FAILURE",

  GET_CURRENT_FOLDER_SUCCESS: "GET_CURRENT_FOLDER_SUCCESS",
  GET_CURRENT_FOLDER_FAILURE: "GET_CURRENT_FOLDER_FAILURE",
};

export const asyncBookmarkTypes = {
  GET_BOOKMARKS_SUCCESS: "GET_BOOKMARKS_SUCCESS",
  GET_BOOKMARKS_FAILURE: "GET_BOOKMARKS_FAILURE",

  CREATE_BOOKMARK_SUCCESS: "CREATE_BOOKMARK_SUCCESS",
  CREATE_BOOKMARK_FAILURE: "CREATE_BOOKMARK_FAILURE",
};
