export const asyncAuthTypes = {
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_REQUEST: "LOGIN_REQUEST",

  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE: "REGISTRATION_FAILURE",
  REGISTRATION_REQUEST: "REGISTRATION_REQUEST",

  GET_ME_FAILURE: "GET_ME_FAILURE",
  GET_ME_SUCCESS: "GET_ME_SUCCESS",
  GET_ME_REQUEST: "GET_ME_REQUEST",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOGOUT_REQUEST: "LOGOUT REQUEST",

  LOGIN: "/login",
  DASHBOARD: "/dashboard",
};

export const asyncFolderTypes = {
  GET_MY_FOLDERS_SUCCESS: "GET_MY_FOLDERS_SUCCESS",
  GET_MY_FOLDERS_FAILURE: "GET_MY_FOLDERS_FAILURE",
  GET_MY_FOLDERS_REQUEST: "GET_MY_FOLDERS_REQUEST",

  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  CREATE_FOLDER_FAILURE: "CREATE_FOLDER_FAILURE",
  CREATE_FOLDER_REQUEST: "CREATE_FOLDER_REQUEST",

  RENAME_FOLDER_SUCCESS: "RENAME_FOLDER_SUCCESS",
  RENAME_FOLDER_FAILURE: "RENAME_FOLDER_FAILURE",
  RENAME_FOLDER_REQUEST: "RENAME_FOLDER_REQUEST",

  GET_FOLDER_CHILDREN_SUCCESS: "GET_FOLDER_CHILDREN_SUCCESS",
  GET_FOLDER_CHILDREN_FAILURE: "GET_FOLDER_CHILDREN_FAILURE",
  GET_FOLDER_CHILDREN_REQUEST: "GET_FOLDER_CHILDREN_REQUEST",

  GET_CURRENT_FOLDER_SUCCESS: "GET_CURRENT_FOLDER_SUCCESS",
  GET_CURRENT_FOLDER_FAILURE: "GET_CURRENT_FOLDER_FAILURE",
  GET_CURRENT_FOLDER_REQUEST: "GET_CURRENT_FOLDER_REQUEST",

  SET_SUBFOLDER_ID: "SET_SUBFOLDER_ID",
  SET_RENAMEFOLDER_ID: "SET_RENAMEFOLDER_ID",
  CLOSE_MODAL: "CLOSE_MODAL",
  CLOSE_RENAME_MODAL: "CLOSE_RENAME_MODAL",
};

export const asyncBookmarkTypes = {
  GET_BOOKMARKS_SUCCESS: "GET_BOOKMARKS_SUCCESS",
  GET_BOOKMARKS_FAILURE: "GET_BOOKMARKS_FAILURE",
  GET_BOOKMARKS_REQUEST: "GET_BOOKMARKS_REQUEST",

  CREATE_BOOKMARK_SUCCESS: "CREATE_BOOKMARK_SUCCESS",
  CREATE_BOOKMARK_FAILURE: "CREATE_BOOKMARK_FAILURE",
  CREATE_BOOKMARK_REQUEST: "CREATE_BOOKMARK_REQUEST",
};
