export const authConst = {
  LOGIN_DETAILS: "LOGIN_DETAILS",
  LOGIN_DETAILS_FAILED: "LOGIN_DETAILS_FAILED",
  LOGIN_DETAILS_SUCCESS: "LOGIN_DETAILS_SUCCESS",

  REGISTRATION_DETAILS: "REGISTRATION_DETAILS",
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",

  GET_ME_REQUEST: "GET_ME_REQUEST",
  GET_ME_FAILURE: "GET_ME_FAILURE",
  GET_ME_SUCCESS: "GET_ME_SUCCESS",
  
  LOGOUT_REQUEST: "LOGOUT REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",
};
