export const authConst = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  REGISTRATION_REQUEST: "REGISTRATION_REQUEST",
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE: "REGISTRATION_FAILURE",

  GET_ME_REQUEST: "GET_ME_REQUEST",
  GET_ME_FAILURE: "GET_ME_FAILURE",
  GET_ME_SUCCESS: "GET_ME_SUCCESS",
  
  LOGOUT_REQUEST: "LOGOUT REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",
};
