export const bookmarkConst = {
  GET_BOOKMARKS_REQUEST: "GET_BOOKMARKS_REQUEST",
  GET_BOOKMARKS_SUCCESS: "GET_BOOKMARKS_SUCCESS",
  GET_BOOKMARKS_FAILURE: "GET_BOOKMARKS_FAILURE",
  
  CREATE_BOOKMARK_REQUEST: "CREATE_BOOKMARK_REQUEST",
  CREATE_BOOKMARK_SUCCESS: "CREATE_BOOKMARK_SUCCESS",
  CREATE_BOOKMARK_FAILURE: "CREATE_BOOKMARK_FAILURE",
};
