export const LOGIN_DETAILS = "login details";
export const LOGIN_DETAILS_FAILED = "login_details_failed";
export const LOGIN_DETAILS_SUCCESS = "login_details_success";
export const REGISTRATION_DETAILS = "registration_details";
export const REGISTRATION_SUCCESS = "registration_success";
export const REGISTRATION_FAILED = "registration_failed";
export const GET_ME = "get_me";
export const GET_ME_FAILURE = "get_me_failure";
export const GET_ME_SUCCESS = "get_me_success";
