export const folderConst = {
  GET_MY_FOLDERS_REQUEST: "GET_MY_FOLDERS_REQUEST",
  GET_MY_FOLDERS_SUCCESS: "GET_MY_FOLDERS_SUCCESS",
  GET_MY_FOLDERS_FAILURE: "GET_MY_FOLDERS_FAILURE",

  CREATE_FOLDER_REQUEST: "CREATE_FOLDER_REQUEST",
  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  CREATE_FOLDER_FAILURE: "CREATE_FOLDER_FAILURE",

  RENAME_FOLDER_REQUEST: "RENAME_FOLDER_REQUEST",
  RENAME_FOLDER_SUCCESS: "RENAME_FOLDER_SUCCESS",
  RENAME_FOLDER_FAILURE: "RENAME_FOLDER_FAILURE",

  ADD_SUBFOLDER_REQUEST: "ADD_SUBFOLDER_REQUEST",

  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  OPEN_RENAME_MODAL: "OPEN_RENAME_MODAL",
  CLOSE_RENAME_MODAL: "CLOSE_RENAME_MODAL",
  
  GET_FOLDER_CHILDREN_REQUEST: "GET_FOLDER_CHILDREN_REQUEST",
  GET_FOLDER_CHILDREN_SUCCESS: "GET_FOLDER_CHILDREN_SUCCESS",
  GET_FOLDER_CHILDREN_FAILURE: "GET_FOLDER_CHILDREN_FAILURE",
  
  GET_CURRENT_FOLDER_REQUEST: "GET_CURRENT_FOLDER_REQUEST",
  GET_CURRENT_FOLDER_SUCCESS: "GET_CURRENT_FOLDER_SUCCESS",
  GET_CURRENT_FOLDER_FAILURE: "GET_CURRENT_FOLDER_FAILURE",
};
