export const syncAuthTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  REGISTRATION_REQUEST: "REGISTRATION_REQUEST",
  GET_ME_REQUEST: "GET_ME_REQUEST",
  LOGOUT_REQUEST: "LOGOUT REQUEST",
  USE_GET_ME: "USE_GET_ME",
};

export const syncFolderTypes = {
  GET_MY_FOLDERS_REQUEST: "GET_MY_FOLDERS_REQUEST",
  CREATE_FOLDER_REQUEST: "CREATE_FOLDER_REQUEST",
  RENAME_FOLDER_REQUEST: "RENAME_FOLDER_REQUEST",
  SET_PARENT_ID: "SET_PARENT_ID",

  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  OPEN_RENAME_MODAL: "OPEN_RENAME_MODAL",
  CLOSE_RENAME_MODAL: "CLOSE_RENAME_MODAL",
  OPEN_FOLDER_MODAL : "OPEN_FOLDER_MODAL",
  CLOSE_FOLDER_MODAL: "CLOSE_FOLDER_MODAL",
  GET_FOLDER_CHILDREN_REQUEST: "GET_FOLDER_CHILDREN_REQUEST",
  GET_CURRENT_FOLDER_REQUEST: "GET_CURRENT_FOLDER_REQUEST",
};

export const syncBookmarkTypes = {
  GET_BOOKMARKS_REQUEST: "GET_BOOKMARKS_REQUEST",
  CREATE_BOOKMARK_REQUEST: "CREATE_BOOKMARK_REQUEST",
};
